# Generated by Django 6.0.2 on 2026-02-25 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_category_post_slug_author_post_author_post_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='country',
            field=models.CharField(default='Test', max_length=30),
            preserve_default=False,
        ),
    ]
