# Generated by Django 6.0.2 on 2026-02-27 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_remove_post_category_post_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='profile_picture',
            field=models.ImageField(default='Some Value', upload_to='profile_pics/'),
            preserve_default=False,
        ),
    ]
